spring:
  application:
    name: book
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
logging:
  level:
    com:
      jdum:
        booking: INFO

booking.fare.url: http://fares/fares
