spring:
  application:
    name: fares
  rabbitmq:
    host: myhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
logging:
  level:
    com:
      jdum:
        booking: INFO
