spring:
  application:
    name: search
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://myhost:8761/eureka/
logging:
  level:
    com:
      jdum:
        booking: ERROR
