spring:
  application:
    name: search-apigateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://myhost:8761/eureka/
zuul:
  routes:
    search-apigateway:
      serviceId: search
      path: /api/**