spring:
  application:
    name: fares-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:h2:mem:faresdb
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://myhost:8761/eureka/

logging:
  level:
    com:
      jdum:
        booking: INFO
